const Report = {

  generate(client, classification, diagnostics, plan) {
    const date = new Date().toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric'
    });

    return {
      meta: {
        name: client.profile.fullName || 'Client',
        date,
        clientType: client.profile.clientType
      },
      sections: {
        pathway:              this._pathwaySection(client, classification),
        limiters:             this._limitersSection(classification.limiters),
        diagnosticSummary:    this._diagnosticsSection(diagnostics),
        movementConsid:       this._movementSection(client),
        programmingPriorities:this._prioritiesSection(client, classification, diagnostics),
        structuredPlan:       this._planSection(plan),
        targetsKPIs:          this._targetsSection(client, classification),
        statedGoals:          this._goalsSection(client),
        injurySummary:        this._injurySection(client)
      }
    };
  },

  render(reportData, containerId) {
    const el = document.getElementById(containerId);
    if (!el) return;

    const { meta, sections } = reportData;
    const order = [
      'pathway', 'limiters', 'diagnosticSummary', 'movementConsid',
      'programmingPriorities', 'structuredPlan', 'targetsKPIs',
      'statedGoals', 'injurySummary'
    ];

    let html = `
      <div class="report-doc">
        <div class="report-header">
          <div class="report-brand">Performance Intelligence System</div>
          <div class="report-info">
            <div class="report-client-name">${this._esc(meta.name)}</div>
            <div class="report-date">Report generated: ${meta.date}</div>
          </div>
        </div>
        <div class="report-body">
    `;

    order.forEach((key, idx) => {
      const sec = sections[key];
      if (!sec) return;
      html += `
        <div class="rs" id="rs-${key}">
          <div class="rs-num">${String(idx + 1).padStart(2, '0')}</div>
          <div class="rs-inner">
            <h3 class="rs-title">${sec.title}</h3>
            <div class="rs-body">${sec.content}</div>
          </div>
        </div>
      `;
    });

    html += `
        </div>
        <div class="report-footer">
          <p>Generated by Performance Intelligence System &mdash; ${meta.date}</p>
          <p>This report is intended for use by qualified fitness and health professionals.</p>
        </div>
      </div>
    `;

    el.innerHTML = html;
  },

  exportPDF() {
    window.print();
  },

  // -----------------------------------------------------------------------
  // Section builders
  // -----------------------------------------------------------------------

  _pathwaySection(client, cls) {
    const { pathway, phase, rationale, strengthLevel, conditioningLevel } = cls;
    const p = client.profile;

    const grid = [
      ['Client Type',       this._clientTypeLabel(p.clientType)],
      ['Assigned Pathway',  pathway],
      ['Current Phase',     phase],
      ['Strength Level',    Classification.strengthLabel(strengthLevel)],
      ['Conditioning',      Classification.conditioningLabel(conditioningLevel)],
      ['Training Age',      p.trainingAge ? p.trainingAge + ' years' : 'Not specified'],
      ['Age / Sex',         [p.age, p.sex].filter(Boolean).join(' / ') || 'Not specified'],
      ['Body Weight',       p.weight ? p.weight + ' kg' : 'Not specified']
    ].map(([label, value]) => `
      <div class="ci-item">
        <span class="ci-label">${label}</span>
        <span class="ci-value">${value}</span>
      </div>
    `).join('');

    return {
      title: 'Pathway Classification',
      content: `
        <div class="pathway-tags">
          <span class="tag tag-pathway">${pathway}</span>
          <span class="tag tag-phase">${phase}</span>
        </div>
        <p class="rationale">${rationale}</p>
        <div class="ci-grid">${grid}</div>
      `
    };
  },

  _limitersSection(limiters) {
    if (!limiters || !limiters.length) {
      return {
        title: 'Primary Limiters',
        content: '<p>No significant limiters identified from available data. Continue monitoring and re-assess at Phase 2 entry.</p>'
      };
    }

    const priorityLabel = p =>
      p === 0 ? 'CRITICAL' : p === 1 ? 'HIGH' : p === 2 ? 'MODERATE' : 'LOW';
    const priorityClass = p =>
      p === 0 ? 'crit' : p === 1 ? 'high' : p === 2 ? 'med' : 'low';

    const items = limiters.map((l, i) => `
      <div class="limiter pri-${priorityClass(l.priority)}">
        <div class="limiter-head">
          <span class="limiter-rank">${i + 1}</span>
          <span class="limiter-cat">${l.category}</span>
          <span class="pri-badge">${priorityLabel(l.priority)}</span>
        </div>
        <p class="limiter-finding">${l.finding}</p>
        <p class="limiter-action"><strong>Action:</strong> ${l.recommendation}</p>
      </div>
    `).join('');

    return { title: 'Primary Limiters', content: items };
  },

  _diagnosticsSection(diagnostics) {
    if (!diagnostics.available) {
      return {
        title: 'Diagnostic Summary',
        content: `<div class="info-box"><p>${diagnostics.summary}</p></div>`
      };
    }

    let out = '';

    if (diagnostics.flags && diagnostics.flags.length) {
      const flagItems = diagnostics.flags.map(f => `
        <div class="diag-flag sev-${f.severity}">
          <span class="flag-device">${f.device}</span>
          <span class="flag-text">${f.flag}</span>
        </div>
      `).join('');
      out += `<div class="diag-flags-block"><h4>Flagged Items</h4>${flagItems}</div>`;
    }

    if (diagnostics.findings && diagnostics.findings.length) {
      out += `<div class="diag-findings">
        ${diagnostics.findings.map(f => `<p>${f}</p>`).join('')}
      </div>`;
    }

    if (diagnostics.recommendations && diagnostics.recommendations.length) {
      const items = diagnostics.recommendations.map(r => `<li>${r}</li>`).join('');
      out += `<div class="diag-recs"><h4>Diagnostic-Driven Programming Implications</h4><ul>${items}</ul></div>`;
    }

    return { title: 'Diagnostic Summary', content: out };
  },

  _movementSection(client) {
    const mv = client.movement;
    const rows = [
      ['Mobility Restrictions',      mv.mobilityRestrictions,  false],
      ['Stability Deficits',         mv.stabilityDeficits,     false],
      ['Movement Literacy',          mv.coordinationLiteracy,  false],
      ['Pain with Movement',         mv.painWithMovement,      true ],
      ['Balance / Proprioception',   mv.balanceNotes,          false]
    ].filter(([, v]) => v && v.trim().length > 2);

    const content = rows.length
      ? rows.map(([label, value, isPain]) =>
          `<div class="mv-row ${isPain ? 'mv-pain' : ''}">
             <strong>${label}:</strong> <span>${value}</span>
           </div>`
        ).join('')
      : '<p>No specific movement concerns documented. Continue standard screening protocol at Phase 1 entry.</p>';

    return { title: 'Movement & Tissue Considerations', content };
  },

  _prioritiesSection(client, cls, diagnostics) {
    const { pathway, phase, limiters, strengthLevel, conditioningLevel } = cls;
    const hasPain = Classification._hasPain(client);
    const items   = [];
    let rank = 1;

    if (hasPain) {
      items.push({ rank: rank++, cls: 'p-crit',
        text: 'Clinical clearance and pain management — no progressive loading until pain-free baseline is established and confirmed across multiple sessions.' });
    }

    if (client.movement.mobilityRestrictions || client.movement.stabilityDeficits) {
      items.push({ rank: rank++, cls: 'p-high',
        text: 'Movement quality restoration — address mobility and stability deficits before applying progressive external load. Movement precedes loading.' });
    }

    if (['very_low', 'low'].includes(strengthLevel)) {
      items.push({ rank: rank++, cls: 'p-high',
        text: 'Foundational strength development — progressive compound loading across squat, hinge, push, and pull patterns. Posterior chain emphasis.' });
    }

    if (['poor', 'below_average'].includes(conditioningLevel)) {
      items.push({ rank: rank++, cls: 'p-med',
        text: 'Aerobic base development — structured Zone 2 conditioning integrated from Phase 1. Work capacity building is a prerequisite for intensity-based programming.' });
    }

    if (diagnostics.available && diagnostics.flags) {
      diagnostics.flags
        .filter(f => f.severity === 'high')
        .forEach(f => {
          items.push({ rank: rank++, cls: 'p-high',
            text: `Address ${f.device} flag: ${f.flag}` });
        });
    }

    if (pathway === 'Return to Performance') {
      items.push({ rank: rank++, cls: 'p-med',
        text: 'Force-velocity profile optimisation — ensure power output is expressed at sport-relevant velocities. Speed-strength zone work is prioritised in Phase 2.' });
      items.push({ rank: rank++, cls: 'p-med',
        text: 'Reactive and deceleration capacity — deceleration and change-of-direction demands must match braking force output confirmed via force plate data.' });
    }

    if (pathway === 'Return to Sport' || pathway === 'Return to Participation') {
      items.push({ rank: rank++, cls: 'p-med',
        text: 'Sport-specific movement pattern integration — progressive exposure to game demands. Condition before compete.' });
    }

    if (pathway === 'Return to Work / Occupation' || pathway === 'Return to ADLs') {
      items.push({ rank: rank++, cls: 'p-med',
        text: 'Functional task tolerance — simulate occupational or daily living demands progressively in a controlled training environment before full return.' });
    }

    if (!items.length) {
      items.push({ rank: 1, cls: 'p-med',
        text: 'Continue progressive overload across primary movement patterns with structured deload at weeks 4–5.' });
      items.push({ rank: 2, cls: 'p-low',
        text: 'Maintain and progressively develop aerobic conditioning base.' });
    }

    const content = items.map(i =>
      `<div class="prio-item ${i.cls}">
         <span class="prio-rank">${i.rank}</span>
         <span class="prio-text">${i.text}</span>
       </div>`
    ).join('');

    return { title: 'Programming Priorities', content };
  },

  _planSection(plan) {
    const phaseHTML = ph => `
      <div class="plan-phase">
        <h4 class="pp-name">${ph.name}</h4>
        <div class="pp-grid">
          <div class="pp-row"><span class="pp-label">Duration</span><span class="pp-val">${ph.duration}</span></div>
          <div class="pp-row full"><span class="pp-label">Objective</span><span class="pp-val">${ph.objective}</span></div>
          <div class="pp-row"><span class="pp-label">Weekly Structure</span><span class="pp-val">${ph.weeklyStructure}</span></div>
          <div class="pp-row"><span class="pp-label">Intensity / Load</span><span class="pp-val">${ph.intensityGuidance}</span></div>
          <div class="pp-row full">
            <span class="pp-label">Exercise Emphasis</span>
            <ul class="pp-list">${ph.exerciseEmphasis.map(e => `<li>${e}</li>`).join('')}</ul>
          </div>
          <div class="pp-row full"><span class="pp-label">Conditioning Emphasis</span><span class="pp-val">${ph.conditioningEmphasis}</span></div>
          ${ph.constraints ? `<div class="pp-row full pp-caution"><span class="pp-label">Key Caution</span><span class="pp-val">${ph.constraints}</span></div>` : ''}
        </div>
      </div>
    `;

    let extra = '';
    if (plan.progressionCriteria && plan.progressionCriteria.length) {
      extra += `<div class="plan-extra">
        <h4>Phase Progression Criteria</h4>
        <ul>${plan.progressionCriteria.map(c => `<li>${c}</li>`).join('')}</ul>
      </div>`;
    }
    if (plan.keyConstraints && plan.keyConstraints.length) {
      extra += `<div class="plan-extra plan-constraints">
        <h4>Key Programme Constraints</h4>
        <ul>${plan.keyConstraints.map(c => `<li>${c}</li>`).join('')}</ul>
      </div>`;
    }

    return {
      title: 'Structured 2-Phase Plan',
      content: phaseHTML(plan.phase1) + phaseHTML(plan.phase2) + extra
    };
  },

  _targetsSection(client, cls) {
    const { pathway, strengthLevel, conditioningLevel } = cls;
    const wt       = parseFloat(client.profile.weight);
    const vo2now   = parseFloat(client.metrics.vo2max);
    const isAthlete = ['Return to Participation','Return to Sport','Return to Performance'].includes(pathway);
    const targets = [];
    const kpis    = [];

    if (wt) {
      if (['very_low', 'low'].includes(strengthLevel)) {
        targets.push(`Squat: achieve ${Math.round(wt * 1.0)} kg (1.0× BW) within Phase 2`);
        targets.push(`Deadlift: achieve ${Math.round(wt * 1.25)} kg (1.25× BW) within Phase 2`);
      } else if (strengthLevel === 'moderate') {
        targets.push(`Squat: progress to ${Math.round(wt * 1.5)} kg (1.5× BW) as Phase 2 target`);
        targets.push(`Deadlift: progress to ${Math.round(wt * 1.75)} kg (1.75× BW) as Phase 2 target`);
      } else if (strengthLevel === 'advanced') {
        targets.push('Maintain current absolute strength levels while improving power expression and velocity outputs');
      }
    }

    if (['poor','below_average'].includes(conditioningLevel)) {
      targets.push(vo2now
        ? `VO2 max: improve from ${vo2now} to ${Math.round(vo2now * 1.15)} ml/kg/min within 8–12 weeks`
        : 'VO2 max: achieve ≥38 ml/kg/min as general health threshold target'
      );
    }

    if (isAthlete) {
      targets.push('Limb symmetry index: ≥90% across ForceDecks, NordBord, and ForceFrame profiles before return to full training');
      targets.push('Linear acceleration: 10 m sprint within 5% of pre-injury or positional norm benchmark');
    }

    kpis.push('Movement quality: ≥8/10 across primary patterns, assessed at each phase entry');
    kpis.push('Attendance: ≥80% session completion across both phases');
    kpis.push('Pain: consistent NRS ≤2/10 during all training by end of Phase 1');
    kpis.push('Subjective readiness: ≥7/10 on training day across most training days');
    if (isAthlete) kpis.push('Diagnostic re-testing: full assessment battery at Phase 1 exit and Phase 2 exit');

    const tHTML = targets.length
      ? `<div class="tgt-block"><h4>Performance Targets</h4><ul>${targets.map(t => `<li>${t}</li>`).join('')}</ul></div>`
      : '';
    const kHTML = `<div class="tgt-block"><h4>Key Performance Indicators</h4><ul>${kpis.map(k => `<li>${k}</li>`).join('')}</ul></div>`;

    return { title: 'Targets & KPIs', content: tHTML + kHTML };
  },

  _goalsSection(client) {
    const goals  = client.profile.goals || 'Not specified.';
    const occup  = client.profile.occupation || '';
    return {
      title: 'Stated Goals',
      content: `<p>${this._esc(goals)}</p>` +
        (occup ? `<p><strong>Occupation / Sport context:</strong> ${this._esc(occup)}</p>` : '')
    };
  },

  _injurySection(client) {
    const injury = client.profile.injuryHistory || 'No injury history documented.';
    const pain   = client.movement.painWithMovement || 'None reported.';
    return {
      title: 'Injury & Limitation Summary',
      content: `
        <div class="inj-grid">
          <div class="inj-item"><strong>Injury History / Limitations:</strong><p>${this._esc(injury)}</p></div>
          <div class="inj-item"><strong>Current Pain with Movement:</strong><p>${this._esc(pain)}</p></div>
        </div>
        <p class="inj-note">All programming must account for the above. Clinician sign-off is required before advancing to Phase 2 where active pain or recent injury is present.</p>
      `
    };
  },

  // -----------------------------------------------------------------------
  // Utilities
  // -----------------------------------------------------------------------

  _esc(str) {
    return String(str || '')
      .replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  },

  _clientTypeLabel(ct) {
    return {
      general_population:    'General Population Adult',
      youth:                 'Youth / First-Time Gym User',
      rehabilitation:        'Rehabilitation Client',
      occupational:          'Occupational / Return-to-Work',
      athlete_participation: 'Athlete — Return to Participation',
      athlete_sport:         'Athlete — Return to Sport',
      athlete_performance:   'Athlete — Return to Performance'
    }[ct] || (ct || 'Not specified');
  }
};
